#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=spiking-model-packager \
-v "$(pwd)":/usr/src/app \
-v "$(pwd)/../spiking-model-configuration/configuration/:/configuration" \
-v "$(pwd)/../spiking-model-configuration/configuration/utils/:/usr/src/app/utils" \
-v "/media/louis/Elements/spiking-model-templates/:/templates" \
-p 5004:5000 \
louisross/spiking-model-packager:1.0 \
bash
