#!/bin/bash

# Update and install node and npm
apt-get update
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs
apt-get install -y npm

#RUN npm install --production
npm install
npm install
